### PR TITLE
83 - Archived projects endpoint is now sorted

### LINKED ISSUE #83: [BUG] - The ArchivedProjects page should sort projects by ID
**Describe the bug**
The archivedProjects page does not sort projects by ID

**To Reproduce**
1. Go to /professor and add 2 projects
2. Archive the second project and then archive the first project
3. Visit /archivedProjects

**Expected behavior**
The archived projects should be sorted by ID

**Actual behavior**
The archived projects are sorted by most recently archived

**Screenshots**
image

### PR DESCRIPTION
**Pull request by blessingomotayo**
## Proposed changes

Archived projects endpoint is now sorted

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._
- [x] The title is in the format [Issue number]-[Issue Title]
- [x] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have moved issue to the “Need review” columns of projects

## Tasks completed
- Archived projects endpoint is sorted

## Tests performed
- none

## Known issues
Create issue for known issues and link them in the pull request

Closes #83 

## Screenshots (if applicable)
Include screenshots of the front-end changes that were made

## Must Do Before Approving
_Put an `x` in the boxes that apply.
- [x] Review the code changes and check for code smells and or make comments if needed

Put an `x` in the box below if you need the reviewer to double check the front-end changes you made
- [x] Tophat Needed (Steps: checkout the branch and run the application locally to determine if the front-end change looks the same as in this PR)

### CODE REVIEW

File: src/main/java/com/eggplant/emoji/repository/ProjectRepository.java [hunk 1]
```diff
@@ -21,6 +21,5 @@
 
     @Modifying
```
Comment (arungalva) [inline src/main/java/com/eggplant/emoji/repository/ProjectRepository.java]: I don't think you need these two annotations. The query is not modifying or needs to be transactional
